fj_2024_lesson_12
g1S0/task1 pull request #10
Opened 2024-11-07 11:03 UTC by g1S0

jwt.secretKey я могу добавить через переменную окружения и также оставил дефолтный вариант. В промышленной разработке так делать не стоит, но здесь я его вставил чтобы полегче чутка было

2024-11-08 15:57 UTC, SHvatov requested changes
@g1S0 👍, оставил пару комментариев - посмотри их, пж

2024-11-08 15:57 UTC, SHvatov commented on README.md
> +# Документация для AuthController и UserController
🔥

2024-11-08 15:57 UTC, SHvatov commented on src/main/java/org/tbank/hw8/configuration/ApplicationConfig.java
> +public class ApplicationConfig {
`SecutiryConfig` - более классическое и говорящее название

2024-11-08 15:57 UTC, SHvatov commented on src/main/java/org/tbank/hw8/configuration/JwtAuthenticationFilter.java
> +        final String jwt;
зачем так рано объявлять эти переменные?

2024-11-08 15:57 UTC, SHvatov commented on src/main/java/org/tbank/hw8/configuration/JwtAuthenticationFilter.java
> +        jwt = authHeader.substring(7);
7 -> "Authorization".length, а "Authorization" -> в константу (в спринге уже есть много готовых)

2024-11-08 15:57 UTC, SHvatov commented on src/main/java/org/tbank/hw8/configuration/JwtAuthenticationFilter.java
> +            if (jwtService.isTokenValid(jwt, userDetails) && isTokenValid) {
Я бы поменял последовательность, а то так можно БД задудосить чисто кидая тебе невалидные токены. Сначала стоит проверить, что токен валидный с помощью сервиса, а потом уже пойти в БД и проверить - не протух ли он. Но зачастую такая информацию кодируется в сам токен, просто тело токена подписано публичным ключом, а на сервере есть приватный ключ, с помощью которого токен можно расшифровать.

2024-11-08 15:57 UTC, SHvatov commented on src/main/java/org/tbank/hw8/configuration/SecurityConfiguration.java
> +public class SecurityConfiguration {
Почему бы тут и не объявить все те бины, что у тебя в AppConfig лежат.

2024-11-08 15:57 UTC, SHvatov commented on src/main/java/org/tbank/hw8/controller/UserController.java
> +        if (!request.getCode().equals("0000")) {
Константа

2024-11-08 15:57 UTC, SHvatov commented on src/main/java/org/tbank/hw8/entity/Token.java
> +    public boolean expired;
А кто отвечает за устаревание токена?

2024-11-08 15:57 UTC, SHvatov commented on src/main/java/org/tbank/hw8/entity/TokenType.java
> +public enum TokenType {
В данном случае избыточно наверное, ибо других вариантов не будет)

2024-11-08 15:57 UTC, SHvatov commented on src/main/java/org/tbank/hw8/repository/TokenRepository.java
> +    Optional<Token> findByToken(String token);
Искать токен по токену - тавтология 

`findByTokenValue`, раз токен это у нас более высокоуровневая структура данных

2024-11-08 15:57 UTC, SHvatov commented on src/main/java/org/tbank/hw8/service/AuthService.java
> +public class AuthService {
Кажется, что где-то не хватает транзакционности)

2024-11-11 13:38 UTC, g1S0 commented on src/main/java/org/tbank/hw8/entity/Token.java
> +    public boolean expired;
Да, можно убрать этот параметр

2024-11-25 13:00 UTC, merged