fj_2024_lesson_2
g1S0/task1 pull request #2
Opened 2024-09-03 13:26 UTC by g1S0

2024-09-05 07:02 UTC, SHvatov requested changes
@g1S0 пара минорных комментариев, в остальном все ок)

2024-09-05 07:02 UTC, SHvatov commented on json/city-error.json
> +{
Давай унесем эти файлы в `resources`?

2024-09-05 07:02 UTC, SHvatov commented on build.gradle
> +    implementation 'ch.qos.logback:logback-classic:1.4.14'
Одного `slf4j` было бы достаточно

2024-09-05 07:02 UTC, SHvatov commented on src/main/java/org/tbank/service/impl/LocationParserImpl.java
> +    public void toXML(Location objectToParse, String filePath) throws RuntimeException {
🔥

2024-09-05 07:28 UTC, g1S0 commented on json/city-error.json
> +{
Да, давай перенесем. Вот так имеется в виду?
![Screenshot 2024-09-05 at 10 27 17 AM](https://github.com/user-attachments/assets/9c305c35-5f58-4ebe-ae7d-c73c1c2d53cb)

2024-09-13 17:56 UTC, merged

2024-09-21 16:04 UTC, SHvatov commented on json/city-error.json
> +{
ага