fj_2024_lesson_8
g1S0/task1 pull request #6
Opened 2024-10-09 22:25 UTC by g1S0

2024-10-13 16:09 UTC, SHvatov requested changes
@g1S0 👍, оставил пару комментариев, погляди их плиз)

2024-10-13 16:09 UTC, SHvatov commented on src/main/java/org/tbank/hw8/client/ApiClient.java
> +
пустая строка как-будто лишняя)

2024-10-13 16:09 UTC, SHvatov commented on src/main/java/org/tbank/hw8/client/ApiClient.java
> +public class ApiClient {
хотя бы `CurrencyApiClient`, а то не особо понятно, для какого апи клиент)

2024-10-13 16:09 UTC, SHvatov commented on src/main/java/org/tbank/hw8/client/ApiClient.java
> +    private static final Logger logger = LoggerFactory.getLogger(ApiClient.class);
1. Статики идут над обычными полями
2. Может заюзать ломбок?)

2024-10-13 16:09 UTC, SHvatov commented on src/main/java/org/tbank/hw8/client/ApiClient.java
> +                    .uri("/XML_daily.asp")
Стоит вынести в константу

2024-10-13 16:09 UTC, SHvatov commented on src/main/java/org/tbank/hw8/client/ApiClient.java
> +    @CircuitBreaker(name = "currencyApiCircuitBreaker", fallbackMethod = "handleFallback")
И сюда же навесить `Cacheable`, чтобы тут кэшировать результаты запросов?

2024-10-13 16:09 UTC, SHvatov commented on src/main/java/org/tbank/hw8/configuration/CacheConfig.java
> +        Objects.requireNonNull(cacheManager().getCache("currencyRate")).clear();
А зачем `Objects.requireNonNull`? И FYI, но после возникновения исключения, которое не будет перехвачено внутри метода, шедулер прекратит свою работу. А заодно нижележащий поток.

2024-10-13 16:09 UTC, SHvatov commented on src/main/java/org/tbank/hw8/controller/CurrencyController.java
> +public interface CurrencyController {
я бы не делал отдельный интерфейс для контроллера, ибо он сам по себе уже достаточно высокоуровненвая абстракция + этот интерфейс отбирает часть работы у контроллера, связанной с хранением информации об АПИ.

2024-10-13 16:09 UTC, SHvatov commented on src/main/java/org/tbank/hw8/controller/advice/GlobalExceptionHandler.java
> +
не фанат пустых строк, там, где они не особо нужны))

ИМХО, но в первую очередь они нужны для логического разделения, тут же логика единая и атомарная

2024-10-16 09:40 UTC, g1S0 commented
1) Убрал пустые строки
2) Поменял название на CurrencyApiClient
3) Использую аннотацию @Slf4j из lombook для логирования
4) Вынес uri в константу
5) Перенес Cacheable внутрь CurrencyApiClient
6) В методе evictAllCachesAtIntervals добавил проверку на null
7) Убрал interface для контроллера

2024-10-22 18:35 UTC, SHvatov approved these changes
@g1S0 👍

2024-10-25 17:11 UTC, merged